# docker-compose.yml

version: "3.8"
services:
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    restart: unless-stopped
    ports: 
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./migrations/build-db/migration.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pizzadb
      MYSQL_USER: admin
      MYSQL_PASSWORD: abc123456789
      SERVICE_NAME: mysql-db
      SERVICE_TAGS: prod
    networks:
      - internal-net01

  pizza-top-app:
    container_name: pizza-top-app-container
    build: .
    image: pizza-top-app:v1
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_NAME: pizzadb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 'abc123456789'
      MYSQL_PORT: 3306
      SERVICE_NAME: pizza-top-app-service
      SERVICE_TAGS: prod
    networks:
      - internal-net01
        
volumes:
  mysql_data:
networks:
  internal-net01:
    driver: bridge